//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tomenglertde.Wax {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.Wax.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can not create tool window. 的本地化字符串。
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm unique file mapping. 的本地化字符串。
        /// </summary>
        public static string ConfirmUniqueFileMapping {
            get {
                return ResourceManager.GetString("ConfirmUniqueFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new directory node. 的本地化字符串。
        /// </summary>
        public static string CreateANewDirectoryNode {
            get {
                return ResourceManager.GetString("CreateANewDirectoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new file node. 的本地化字符串。
        /// </summary>
        public static string CreateANewFileNode {
            get {
                return ResourceManager.GetString("CreateANewFileNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy symbols 的本地化字符串。
        /// </summary>
        public static string DeploySymbols {
            get {
                return ResourceManager.GetString("DeploySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory 的本地化字符串。
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory mappings 的本地化字符串。
        /// </summary>
        public static string DirectoryMappings {
            get {
                return ResourceManager.GetString("DirectoryMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documentation 的本地化字符串。
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ext. 的本地化字符串。
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File mappings 的本地化字符串。
        /// </summary>
        public static string FileMappings {
            get {
                return ResourceManager.GetString("FileMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projects to install: 的本地化字符串。
        /// </summary>
        public static string ProjectsToInstall {
            get {
                return ResourceManager.GetString("ProjectsToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove custom file mapping. 的本地化字符串。
        /// </summary>
        public static string RemoveCustomFileMapping {
            get {
                return ResourceManager.GetString("RemoveCustomFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the custom mapping. 的本地化字符串。
        /// </summary>
        public static string RemoveTheCustomMapping {
            get {
                return ResourceManager.GetString("RemoveTheCustomMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove unmapped file. 的本地化字符串。
        /// </summary>
        public static string RemoveUnmappedFile {
            get {
                return ResourceManager.GetString("RemoveUnmappedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root directory 的本地化字符串。
        /// </summary>
        public static string RootDirectory {
            get {
                return ResourceManager.GetString("RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup project to edit: 的本地化字符串。
        /// </summary>
        public static string SetupProjectToEdit {
            get {
                return ResourceManager.GetString("SetupProjectToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all projects 的本地化字符串。
        /// </summary>
        public static string ShowAllProjects {
            get {
                return ResourceManager.GetString("ShowAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support the project. 的本地化字符串。
        /// </summary>
        public static string SupportTheProject {
            get {
                return ResourceManager.GetString("SupportTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support the project by writing a short review. 的本地化字符串。
        /// </summary>
        public static string SupportTheProjectByWritingAShortReview {
            get {
                return ResourceManager.GetString("SupportTheProjectByWritingAShortReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiX Setup Editor 的本地化字符串。
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmapped Files 的本地化字符串。
        /// </summary>
        public static string UnmappedFiles {
            get {
                return ResourceManager.GetString("UnmappedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiX definition 的本地化字符串。
        /// </summary>
        public static string WiXDefinition {
            get {
                return ResourceManager.GetString("WiXDefinition", resourceCulture);
            }
        }
    }
}
