//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tomenglertde.Wax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.Wax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm unique file mapping..
        /// </summary>
        public static string ConfirmUniqueFileMapping {
            get {
                return ResourceManager.GetString("ConfirmUniqueFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new directory node..
        /// </summary>
        public static string CreateANewDirectoryNode {
            get {
                return ResourceManager.GetString("CreateANewDirectoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file node..
        /// </summary>
        public static string CreateANewFileNode {
            get {
                return ResourceManager.GetString("CreateANewFileNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string DeploySymbols {
            get {
                return ResourceManager.GetString("DeploySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the debug symbols in the setup project..
        /// </summary>
        public static string DeploySymbolsToolTip {
            get {
                return ResourceManager.GetString("DeploySymbolsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory mappings.
        /// </summary>
        public static string DirectoryMappings {
            get {
                return ResourceManager.GetString("DirectoryMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext. Localizations.
        /// </summary>
        public static string ExternalLocalizations {
            get {
                return ResourceManager.GetString("ExternalLocalizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include also external/3rd party localizations in the setup project..
        /// </summary>
        public static string ExternalLocalizationsToolTip {
            get {
                return ResourceManager.GetString("ExternalLocalizationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File mappings.
        /// </summary>
        public static string FileMappings {
            get {
                return ResourceManager.GetString("FileMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizations.
        /// </summary>
        public static string Localizations {
            get {
                return ResourceManager.GetString("Localizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include localizations in the setup project..
        /// </summary>
        public static string LocalizationsToolTip {
            get {
                return ResourceManager.GetString("LocalizationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects to install:.
        /// </summary>
        public static string ProjectsToInstall {
            get {
                return ResourceManager.GetString("ProjectsToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced by:.
        /// </summary>
        public static string ReferencedBy {
            get {
                return ResourceManager.GetString("ReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove custom file mapping..
        /// </summary>
        public static string RemoveCustomFileMapping {
            get {
                return ResourceManager.GetString("RemoveCustomFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the custom mapping..
        /// </summary>
        public static string RemoveTheCustomMapping {
            get {
                return ResourceManager.GetString("RemoveTheCustomMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unmapped file..
        /// </summary>
        public static string RemoveUnmappedFile {
            get {
                return ResourceManager.GetString("RemoveUnmappedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root directory.
        /// </summary>
        public static string RootDirectory {
            get {
                return ResourceManager.GetString("RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup project to edit:.
        /// </summary>
        public static string SetupProjectToEdit {
            get {
                return ResourceManager.GetString("SetupProjectToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all projects.
        /// </summary>
        public static string ShowAllProjects {
            get {
                return ResourceManager.GetString("ShowAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the project..
        /// </summary>
        public static string SupportTheProject {
            get {
                return ResourceManager.GetString("SupportTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the project by writing a short review..
        /// </summary>
        public static string SupportTheProjectByWritingAShortReview {
            get {
                return ResourceManager.GetString("SupportTheProjectByWritingAShortReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Setup Editor.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmapped Files.
        /// </summary>
        public static string UnmappedFiles {
            get {
                return ResourceManager.GetString("UnmappedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX definition.
        /// </summary>
        public static string WiXDefinition {
            get {
                return ResourceManager.GetString("WiXDefinition", resourceCulture);
            }
        }
    }
}
